# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sahin/Chip8-Emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sahin/Chip8-Emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sahin/Chip8-Emulator/CMakeFiles /home/sahin/Chip8-Emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sahin/Chip8-Emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chip8

# Build rule for target.
chip8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chip8
.PHONY : chip8

# fast build rule for target.
chip8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/build
.PHONY : chip8/fast

src/CPU.o: src/CPU.cpp.o
.PHONY : src/CPU.o

# target to build an object file
src/CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPU.cpp.o
.PHONY : src/CPU.cpp.o

src/CPU.i: src/CPU.cpp.i
.PHONY : src/CPU.i

# target to preprocess a source file
src/CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPU.cpp.i
.PHONY : src/CPU.cpp.i

src/CPU.s: src/CPU.cpp.s
.PHONY : src/CPU.s

# target to generate assembly for a file
src/CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPU.cpp.s
.PHONY : src/CPU.cpp.s

src/CPUTileMapData.o: src/CPUTileMapData.cpp.o
.PHONY : src/CPUTileMapData.o

# target to build an object file
src/CPUTileMapData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPUTileMapData.cpp.o
.PHONY : src/CPUTileMapData.cpp.o

src/CPUTileMapData.i: src/CPUTileMapData.cpp.i
.PHONY : src/CPUTileMapData.i

# target to preprocess a source file
src/CPUTileMapData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPUTileMapData.cpp.i
.PHONY : src/CPUTileMapData.cpp.i

src/CPUTileMapData.s: src/CPUTileMapData.cpp.s
.PHONY : src/CPUTileMapData.s

# target to generate assembly for a file
src/CPUTileMapData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/CPUTileMapData.cpp.s
.PHONY : src/CPUTileMapData.cpp.s

src/Memory.o: src/Memory.cpp.o
.PHONY : src/Memory.o

# target to build an object file
src/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/Memory.cpp.o
.PHONY : src/Memory.cpp.o

src/Memory.i: src/Memory.cpp.i
.PHONY : src/Memory.i

# target to preprocess a source file
src/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/Memory.cpp.i
.PHONY : src/Memory.cpp.i

src/Memory.s: src/Memory.cpp.s
.PHONY : src/Memory.s

# target to generate assembly for a file
src/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/Memory.cpp.s
.PHONY : src/Memory.cpp.s

src/TileMap.o: src/TileMap.cpp.o
.PHONY : src/TileMap.o

# target to build an object file
src/TileMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/TileMap.cpp.o
.PHONY : src/TileMap.cpp.o

src/TileMap.i: src/TileMap.cpp.i
.PHONY : src/TileMap.i

# target to preprocess a source file
src/TileMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/TileMap.cpp.i
.PHONY : src/TileMap.cpp.i

src/TileMap.s: src/TileMap.cpp.s
.PHONY : src/TileMap.s

# target to generate assembly for a file
src/TileMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/TileMap.cpp.s
.PHONY : src/TileMap.cpp.s

src/loadROM.o: src/loadROM.cpp.o
.PHONY : src/loadROM.o

# target to build an object file
src/loadROM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/loadROM.cpp.o
.PHONY : src/loadROM.cpp.o

src/loadROM.i: src/loadROM.cpp.i
.PHONY : src/loadROM.i

# target to preprocess a source file
src/loadROM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/loadROM.cpp.i
.PHONY : src/loadROM.cpp.i

src/loadROM.s: src/loadROM.cpp.s
.PHONY : src/loadROM.s

# target to generate assembly for a file
src/loadROM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/loadROM.cpp.s
.PHONY : src/loadROM.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chip8"
	@echo "... src/CPU.o"
	@echo "... src/CPU.i"
	@echo "... src/CPU.s"
	@echo "... src/CPUTileMapData.o"
	@echo "... src/CPUTileMapData.i"
	@echo "... src/CPUTileMapData.s"
	@echo "... src/Memory.o"
	@echo "... src/Memory.i"
	@echo "... src/Memory.s"
	@echo "... src/TileMap.o"
	@echo "... src/TileMap.i"
	@echo "... src/TileMap.s"
	@echo "... src/loadROM.o"
	@echo "... src/loadROM.i"
	@echo "... src/loadROM.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

